### ISSUE TITLE
raise error.UnregisteredEnv('No registered env with id: {}'.format(id)) gym.error.UnregisteredEnv: No registered env with id: walker_4_flipped-v0

### ISSUE THREAD

**Issue by YimingWangMingle** [yobibyte/amorpheus#2]
Hello, Vitaly.

Thanks for your fantastic work!
I am trying to run experiments with your code, however I was stuck in :
Traceback (most recent call last):
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'walker_4_flipped-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/carla/baselines/baselines/common/vec_env/subproc_vec_env.py", line 15, in worker
    envs = [env_fn_wrapper() for env_fn_wrapper in env_fn_wrappers.x]
  File "/home/carla/baselines/baselines/common/vec_env/subproc_vec_env.py", line 15, in <listcomp>
    envs = [env_fn_wrapper() for env_fn_wrapper in env_fn_wrappers.x]
  File "/home/carla/amorpheus/modular-rl/src/utils.py", line 18, in helper
    e = gym.make("environments:%s-v0" % env_name)
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/carla/anaconda3/envs/mujoco/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: walker_4_flipped-v0

Something wrong with gym.make(), I had tried using different gym versions and  mujuco-py versions like mujoco-py==2.0.2.4 and  mujoco-py==1.50.1.68. It still doesn't work. I wonder if you can give some suggestions.
Thanks for your great work again and I'm looking forward to your reply.

Thank you.

**Comment by LegendFateX** [comment]
Hello there, I've meet the same problem as yours recently, have you solved this?

**Comment by mengnan12** [comment]
Hello vitaly,what a great work,I have come up with the same issue running you code,I also meet the same error as follows:

raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: walker_4_flipped-v0

I cann't be more appreciated if  you can give some suggestions. Thank you! @yobibyte

**Comment by yobibyte** [comment]
Hi everyone, sorry I somehow missed the notification about the issue. Can you, please, provide the exact command for me to replicate the bug?

**Comment by YimingWangMingle** [comment]
> Hi everyone, sorry I somehow missed the notification about the issue. Can you, please, provide the exact command for me to replicate the bug?

Hi, I feel very grateful for your reply, after I set up the environment, I just cd the src folder and:
        python3 main.py \
          --custom_xml environments/walkers \
          --actor_type transformer \
          --critic_type transformer \
          --seed 1 \
          --grad_clipping_value 0.1 \
          --attention_layers 3 \
          --attention_heads 2 \
          --lr 0.0001 \
          --transformer_norm 1 \
          --attention_hidden_size 256 \
          --condition_decoder 1 \
          --label walkers_amorpheus&
After it started training, all the tasks raised error.UnregisteredEnv('No registered env with id: {}'.format(id)),gym.error.UnregisteredEnv: No registered env with id: #task-v0. After the debugging I found all the customized envs were registered successfully but something went wrong with the gym.make(). I had tried using different gym versions and mujuco-py versions like mujoco-py==2.0.2.4 and mujoco-py==1.50.1.68. It still doesn't work. I wonder if you can give some suggestions. Thank you for wasting your time. Looking forward to your reply!

**Comment by yobibyte** [comment]
That's quite weird. I've just run the script in the provided docker container and it works for me. Do you have the same bug if you run the script from src/scripts/amorpheus/walkers_amorpheus.sh?

Also, do you have the pythonpath set up as on the 82th line of the provided Dockerfile?

**Comment by YimingWangMingle** [comment]
> That's quite weird. I've just run the script in the provided docker container and it works for me. Do you have the same bug if you run the script from src/scripts/amorpheus/walkers_amorpheus.sh?
> 
> Also, do you have the pythonpath set up as on the 82th line of the provided Dockerfile?

Thank u for your reply, I had set up PYTHONPATH variable as the provided dockerfile and I got the same bug running the scripts from src/scripts/amorpheus/walkers_amorpheus.sh. I am  still trying to catch the problem. Thank you again for wasting your time.

**Comment by yobibyte** [comment]
That's very weird, can you try to build the docker container and run the script?
